### ISSUE TITLE
Fail to compile error "BOOST_JOIN"

### ISSUE THREAD

**Issue by TurBoss** [KASUYASU/cutsim#2]
Hi

I'm trying to compile the project

here is the output:
```
turboss@TurBoPx:~/Sources/cutsim/build$ cmake ../src
-- setting gcc options: -Wall -Werror -Wno-deprecated -pedantic-errors
--  CMAKE_BUILD_TYPE = Debug
-- Boost version: 1.61.0
-- found Boost: 1_61
-- boost-incude dirs are: /usr/include
-- boost_LIBRARY_DIRS is: /usr/lib
-- Boost_LIBRARIES is: 
-- found OpenMP, compiling with flags: -fopenmp
-- Found QGLViewer: /usr/lib/x86_64-linux-gnu/libQGLViewer-qt4.so
-- Cutting simulation requires OpenGL and Qt4...
-- found OPENGL, lib = /usr/lib/x86_64-linux-gnu/libGLU.so/usr/lib/x86_64-linux-gnu/libGL.so
--  qmake = /usr/bin/qmake
-- QT_USE_FILE = /usr/share/cmake-3.5/Modules/UseQt4.cmake
-- CMAKE_SOURCE_DIR = /home/turboss/Sources/cutsim/src
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
-- QT_USE_FILE = /usr/share/cmake-3.5/Modules/UseQt4.cmake
-- found OPENGL, lib = /usr/lib/x86_64-linux-gnu/libGLU.so/usr/lib/x86_64-linux-gnu/libGL.so
-- Boost version: 1.61.0
-- found Boost: 1_61
-- boost-incude dirs are: /usr/include
--  DOXY_CONFIG = /home/turboss/Sources/cutsim/src/Doxyfile
--  Run 'make doc' to generate documentation.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/turboss/Sources/cutsim/build
turboss@TurBoPx:~/Sources/cutsim/build$ make
[  2%] Generating moc_cutsim.cxx
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
cutsim/CMakeFiles/libcutsim.dir/build.make:67: recipe for target 'cutsim/moc_cutsim.cxx' failed
make[2]: *** [cutsim/moc_cutsim.cxx] Error 1
CMakeFiles/Makefile2:117: recipe for target 'cutsim/CMakeFiles/libcutsim.dir/all' failed
make[1]: *** [cutsim/CMakeFiles/libcutsim.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
Thanks

**Comment by KASUYASU** [comment]
Hi,

Please refer to the next sites.

https://github.com/ros-planning/moveit_ros/issues/653
http://answers.ros.org/question/233786/parse-error-at-boost_join/

I think that you have a version mismatch problem. The next copy is the message when I execute the command "cmake ../src" on my 32bits Linux PC.

hamada@hamada-H97M-S01:~/tmp/cutsim-master/build$ cmake ../src-- setting gcc options: -Wall -Werror -Wno-deprecated -pedantic-errors
--  CMAKE_BUILD_TYPE = Debug
-- Boost version: 1.54.0
-- found Boost: 1_54
-- boost-incude dirs are: /usr/include
-- boost_LIBRARY_DIRS is: /usr/lib
-- Boost_LIBRARIES is: 
-- found OpenMP, compiling with flags: -fopenmp
-- Found QGLViewer: /usr/lib/libQGLViewer.so
-- Cutting simulation requires OpenGL and Qt4...
-- found OPENGL, lib = /usr/lib/i386-linux-gnu/libGLU.so/usr/lib/i386-linux-gnu/libGL.so/usr/lib/i386-linux-gnu/libSM.so/usr/lib/i386-linux-gnu/libICE.so/usr/lib/i386-linux-gnu/libX11.so/usr/lib/i386-linux-gnu/libXext.so
--  qmake = /usr/bin/qmake-qt4
-- QT_USE_FILE = /usr/share/cmake-2.8/Modules/UseQt4.cmake
-- CMAKE_SOURCE_DIR = /home/hamada/tmp/cutsim-master/src
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- QT_USE_FILE = /usr/share/cmake-2.8/Modules/UseQt4.cmake
-- found OPENGL, lib = /usr/lib/i386-linux-gnu/libGLU.so/usr/lib/i386-linux-gnu/libGL.so/usr/lib/i386-linux-gnu/libSM.so/usr/lib/i386-linux-gnu/libICE.so/usr/lib/i386-linux-gnu/libX11.so/usr/lib/i386-linux-gnu/libXext.so
-- Boost version: 1.54.0
-- found Boost: 1_54
-- boost-incude dirs are: /usr/include
--  DOXY_CONFIG = /home/hamada/tmp/cutsim-master/src/Doxyfile
--  Run 'make doc' to generate documentation.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hamada/tmp/cutsim-master/build

Kazu

**Comment by TurBoss** [comment]
thanks

**Comment by stustev** [comment]
Where would I find the software to compile the rs274 with AC you use in cutsim?

**Comment by KASUYASU** [comment]
Hi, 

For the source code, please visit the page

https://github.com/emogenet/rs274ngc

I think you may compile those with normal 'gcc' and 'make'.
If not, please refer the contents of 'Makefile'.

Kazu

**Comment by stustev** [comment]
thanks - I have the zip and a clone - will work on it
